import React from 'react';
import AccommodationCard from './AccommodationCard';

const SearchResults = ({ selectedDestination }) => {
  // Location-specific accommodation data
  const getLocationData = (destination) => {
    // Normalize destination input for better matching
    const normalizedDestination = destination ? destination.toLowerCase().trim() : '';
    
    const locationData = {
      'majorca': {
        accommodations: [
          {
            id: 1,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Beachfront Villa',
            location: 'Palma, Majorca',
            distance: '0.5 km from beach',
            rating: 9.2,
            reviewCount: 45,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€280',
            originalPrice: '€350',
            discount: '-20%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '120m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Beachfront', 'Pool']
          },
          {
            id: 2,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Mountain View Apartment',
            location: 'Valldemossa, Majorca',
            distance: '2.1 km from town center',
            rating: 8.7,
            reviewCount: 23,
            reviewText: 'Very good',
            familyRated: false,
            price: '€180',
            originalPrice: '€220',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '85m²',
            eco: false,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Mountain View', 'Quiet']
          },
          {
            id: 3,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Luxury Resort Suite',
            location: 'Cala d\'Or, Majorca',
            distance: '0.2 km from marina',
            rating: 9.5,
            reviewCount: 67,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€450',
            originalPrice: '€550',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 8 pers.',
            bedrooms: '4 bedroom',
            size: '200m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Luxury', 'Marina View']
          },
          {
            id: 4,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Seaside Cottage',
            location: 'Port de Pollença, Majorca',
            distance: '0.3 km from beach',
            rating: 8.9,
            reviewCount: 34,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€320',
            originalPrice: '€380',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '95m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Seaside', 'Family-friendly']
          },
          {
            id: 5,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Historic Townhouse',
            location: 'Alcúdia, Majorca',
            distance: '0.8 km from old town',
            rating: 8.4,
            reviewCount: 28,
            reviewText: 'Very good',
            familyRated: false,
            price: '€220',
            originalPrice: '€260',
            discount: '-15%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '65m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Historic', 'Charming']
          },
          {
            id: 6,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Golf Resort Villa',
            location: 'Son Vida, Majorca',
            distance: '0.1 km from golf course',
            rating: 9.1,
            reviewCount: 41,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€520',
            originalPrice: '€620',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 8 pers.',
            bedrooms: '4 bedroom',
            size: '180m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Golf', 'Luxury', 'Resort']
          },
          {
            id: 7,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Modern Apartment',
            location: 'Magaluf, Majorca',
            distance: '0.2 km from beach',
            rating: 8.6,
            reviewCount: 19,
            reviewText: 'Very good',
            familyRated: false,
            price: '€190',
            originalPrice: '€230',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '75m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Free cancellation',
            tags: ['Modern', 'Beachfront']
          },
          {
            id: 8,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Countryside Villa',
            location: 'Sóller, Majorca',
            distance: '1.5 km from town center',
            rating: 9.0,
            reviewCount: 52,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€380',
            originalPrice: '€450',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '140m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Countryside', 'Peaceful']
          },
          {
            id: 9,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Boutique Hotel Room',
            location: 'Palma Old Town, Majorca',
            distance: '0.1 km from cathedral',
            rating: 8.8,
            reviewCount: 36,
            reviewText: 'Excellent',
            familyRated: false,
            price: '€160',
            originalPrice: '€200',
            discount: '-20%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '45m²',
            eco: false,
            multiUnit: '5 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Boutique', 'Historic']
          },
          {
            id: 10,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Penthouse with Pool',
            location: 'Cala Major, Majorca',
            distance: '0.4 km from beach',
            rating: 9.3,
            reviewCount: 29,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€480',
            originalPrice: '€580',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '160m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Penthouse', 'Pool', 'Luxury']
          },
          {
            id: 11,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Traditional Finca',
            location: 'Binissalem, Majorca',
            distance: '2.0 km from town center',
            rating: 8.5,
            reviewCount: 31,
            reviewText: 'Very good',
            familyRated: true,
            price: '€350',
            originalPrice: '€420',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 8 pers.',
            bedrooms: '4 bedroom',
            size: '200m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Traditional', 'Rural']
          },
          {
            id: 12,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Studio by the Sea',
            location: 'Cala Millor, Majorca',
            distance: '0.1 km from beach',
            rating: 8.3,
            reviewCount: 22,
            reviewText: 'Very good',
            familyRated: false,
            price: '€140',
            originalPrice: '€170',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '35m²',
            eco: false,
            multiUnit: '4 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Studio', 'Beachfront']
          },
          {
            id: 13,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Luxury Penthouse',
            location: 'Portals Nous, Majorca',
            distance: '0.3 km from marina',
            rating: 9.4,
            reviewCount: 18,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€650',
            originalPrice: '€780',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 8 pers.',
            bedrooms: '4 bedroom',
            size: '220m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Luxury', 'Marina', 'Penthouse']
          },
          {
            id: 14,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Cozy Apartment',
            location: 'Inca, Majorca',
            distance: '1.2 km from town center',
            rating: 8.2,
            reviewCount: 15,
            reviewText: 'Very good',
            familyRated: false,
            price: '€120',
            originalPrice: '€150',
            discount: '-20%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '50m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Cozy', 'Budget']
          }
        ],
        totalCount: 127
      },
      'barcelona': {
        accommodations: [
          {
            id: 1,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Modern City Apartment',
            location: 'Eixample, Barcelona',
            distance: '0.8 km from Sagrada Familia',
            rating: 8.9,
            reviewCount: 34,
            reviewText: 'Excellent',
            familyRated: false,
            price: '€320',
            originalPrice: '€400',
            discount: '-20%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '75m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['City Center', 'Modern']
          },
          {
            id: 2,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Beach House',
            location: 'Barceloneta, Barcelona',
            distance: '0.1 km from beach',
            rating: 9.1,
            reviewCount: 28,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€380',
            originalPrice: '€450',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '110m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Beachfront', 'Family-friendly']
          },
          {
            id: 3,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Gothic Quarter Studio',
            location: 'Ciutat Vella, Barcelona',
            distance: '0.2 km from cathedral',
            rating: 8.7,
            reviewCount: 42,
            reviewText: 'Very good',
            familyRated: false,
            price: '€180',
            originalPrice: '€220',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '40m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Free cancellation',
            tags: ['Historic', 'City Center']
          },
          {
            id: 4,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Luxury Penthouse',
            location: 'Passeig de Gràcia, Barcelona',
            distance: '0.3 km from Casa Batlló',
            rating: 9.3,
            reviewCount: 19,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€580',
            originalPrice: '€700',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '150m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Luxury', 'Historic']
          },
          {
            id: 5,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Beachfront Apartment',
            location: 'Nova Icària, Barcelona',
            distance: '0.1 km from beach',
            rating: 8.8,
            reviewCount: 31,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€420',
            originalPrice: '€500',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '90m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Beachfront', 'Modern']
          },
          {
            id: 6,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Gràcia Loft',
            location: 'Gràcia, Barcelona',
            distance: '0.5 km from Park Güell',
            rating: 8.5,
            reviewCount: 26,
            reviewText: 'Very good',
            familyRated: false,
            price: '€250',
            originalPrice: '€300',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '60m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Loft', 'Artsy']
          },
          {
            id: 7,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Montjuïc Villa',
            location: 'Montjuïc, Barcelona',
            distance: '0.8 km from Magic Fountain',
            rating: 9.0,
            reviewCount: 37,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€480',
            originalPrice: '€580',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 8 pers.',
            bedrooms: '4 bedroom',
            size: '180m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Villa', 'City View']
          },
          {
            id: 8,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Sants Apartment',
            location: 'Sants-Montjuïc, Barcelona',
            distance: '0.3 km from train station',
            rating: 8.3,
            reviewCount: 21,
            reviewText: 'Very good',
            familyRated: false,
            price: '€200',
            originalPrice: '€240',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '70m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Convenient', 'Modern']
          },
          {
            id: 9,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Poble Sec Studio',
            location: 'Poble Sec, Barcelona',
            distance: '0.4 km from Montjuïc',
            rating: 8.1,
            reviewCount: 18,
            reviewText: 'Very good',
            familyRated: false,
            price: '€160',
            originalPrice: '€190',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '35m²',
            eco: false,
            multiUnit: '4 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Budget', 'Central']
          },
          {
            id: 10,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Eixample Penthouse',
            location: 'Eixample, Barcelona',
            distance: '0.5 km from Casa Milà',
            rating: 9.2,
            reviewCount: 24,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€520',
            originalPrice: '€620',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '130m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Penthouse', 'Luxury']
          },
          {
            id: 11,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Sant Antoni Loft',
            location: 'Sant Antoni, Barcelona',
            distance: '0.6 km from market',
            rating: 8.6,
            reviewCount: 29,
            reviewText: 'Very good',
            familyRated: false,
            price: '€280',
            originalPrice: '€340',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '55m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Loft', 'Trendy']
          },
          {
            id: 12,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Port Olímpic Apartment',
            location: 'Port Olímpic, Barcelona',
            distance: '0.2 km from marina',
            rating: 8.9,
            reviewCount: 33,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€380',
            originalPrice: '€460',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '85m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Marina', 'Modern']
          },
          {
            id: 13,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Raval Apartment',
            location: 'El Raval, Barcelona',
            distance: '0.3 km from MACBA',
            rating: 8.4,
            reviewCount: 22,
            reviewText: 'Very good',
            familyRated: false,
            price: '€220',
            originalPrice: '€270',
            discount: '-19%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '50m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Artsy', 'Central']
          },
          {
            id: 14,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Sarrià-Sant Gervasi Villa',
            location: 'Sarrià-Sant Gervasi, Barcelona',
            distance: '1.2 km from city center',
            rating: 9.1,
            reviewCount: 41,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€450',
            originalPrice: '€540',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '120m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Villa', 'Quiet']
          }
        ],
        totalCount: 89
      },
      'paris': {
        accommodations: [
          {
            id: 1,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Charming Studio',
            location: 'Le Marais, Paris',
            distance: '0.3 km from Notre-Dame',
            rating: 8.6,
            reviewCount: 42,
            reviewText: 'Very good',
            familyRated: false,
            price: '€250',
            originalPrice: '€300',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '35m²',
            eco: true,
            multiUnit: '4 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Historic', 'Romantic']
          },
          {
            id: 2,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Luxury Penthouse',
            location: 'Champs-Élysées, Paris',
            distance: '0.5 km from Arc de Triomphe',
            rating: 9.4,
            reviewCount: 19,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€650',
            originalPrice: '€800',
            discount: '-19%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '150m²',
            eco: false,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Luxury', 'City View']
          },
          {
            id: 3,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Montmartre Apartment',
            location: 'Montmartre, Paris',
            distance: '0.2 km from Sacré-Cœur',
            rating: 8.8,
            reviewCount: 35,
            reviewText: 'Excellent',
            familyRated: false,
            price: '€280',
            originalPrice: '€340',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '45m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Artsy', 'Historic']
          },
          {
            id: 4,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Saint-Germain Loft',
            location: 'Saint-Germain-des-Prés, Paris',
            distance: '0.4 km from Luxembourg Gardens',
            rating: 9.0,
            reviewCount: 28,
            reviewText: 'Excellent',
            familyRated: false,
            price: '€420',
            originalPrice: '€500',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '70m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Luxury', 'Cultural']
          },
          {
            id: 5,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Bastille Studio',
            location: 'Bastille, Paris',
            distance: '0.3 km from Place de la Bastille',
            rating: 8.3,
            reviewCount: 24,
            reviewText: 'Very good',
            familyRated: false,
            price: '€200',
            originalPrice: '€240',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '30m²',
            eco: false,
            multiUnit: '3 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Trendy', 'Central']
          },
          {
            id: 6,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Eiffel Tower View Apartment',
            location: '7th arrondissement, Paris',
            distance: '0.8 km from Eiffel Tower',
            rating: 9.2,
            reviewCount: 47,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€580',
            originalPrice: '€700',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '85m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Eiffel Tower', 'Luxury']
          },
          {
            id: 7,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Canal Saint-Martin Apartment',
            location: '10th arrondissement, Paris',
            distance: '0.2 km from Canal Saint-Martin',
            rating: 8.7,
            reviewCount: 31,
            reviewText: 'Very good',
            familyRated: false,
            price: '€320',
            originalPrice: '€380',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '55m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Canal', 'Trendy']
          },
          {
            id: 8,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Latin Quarter Studio',
            location: 'Latin Quarter, Paris',
            distance: '0.3 km from Sorbonne',
            rating: 8.5,
            reviewCount: 26,
            reviewText: 'Very good',
            familyRated: false,
            price: '€220',
            originalPrice: '€270',
            discount: '-19%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '32m²',
            eco: false,
            multiUnit: '4 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Student', 'Historic']
          },
          {
            id: 9,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Belleville Loft',
            location: 'Belleville, Paris',
            distance: '0.5 km from Parc de Belleville',
            rating: 8.4,
            reviewCount: 20,
            reviewText: 'Very good',
            familyRated: false,
            price: '€180',
            originalPrice: '€220',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '40m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Artsy', 'Budget']
          },
          {
            id: 10,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Opéra District Apartment',
            location: '9th arrondissement, Paris',
            distance: '0.4 km from Opéra Garnier',
            rating: 8.9,
            reviewCount: 38,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€450',
            originalPrice: '€540',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '75m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Cultural', 'Luxury']
          },
          {
            id: 11,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Pigalle Apartment',
            location: 'Pigalle, Paris',
            distance: '0.3 km from Moulin Rouge',
            rating: 8.1,
            reviewCount: 17,
            reviewText: 'Very good',
            familyRated: false,
            price: '€190',
            originalPrice: '€230',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '42m²',
            eco: false,
            multiUnit: '3 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Nightlife', 'Central']
          },
          {
            id: 12,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Trocadéro Penthouse',
            location: '16th arrondissement, Paris',
            distance: '0.6 km from Trocadéro',
            rating: 9.3,
            reviewCount: 22,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€720',
            originalPrice: '€860',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '120m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Luxury', 'Eiffel Tower View']
          },
          {
            id: 13,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Marais Loft',
            location: 'Le Marais, Paris',
            distance: '0.4 km from Place des Vosges',
            rating: 8.8,
            reviewCount: 33,
            reviewText: 'Excellent',
            familyRated: false,
            price: '€380',
            originalPrice: '€460',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '60m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Historic', 'Trendy']
          },
          {
            id: 14,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Champs-Élysées Studio',
            location: '8th arrondissement, Paris',
            distance: '0.2 km from Champs-Élysées',
            rating: 8.6,
            reviewCount: 29,
            reviewText: 'Very good',
            familyRated: false,
            price: '€350',
            originalPrice: '€420',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '38m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Luxury', 'Shopping']
          }
        ],
        totalCount: 156
      },
      // Spain country mapping
      'spain': {
        accommodations: [
          {
            id: 1,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Historic Apartment',
            location: 'Madrid, Spain',
            distance: '0.3 km from Puerta del Sol',
            rating: 8.8,
            reviewCount: 42,
            reviewText: 'Excellent',
            familyRated: false,
            price: '€220',
            originalPrice: '€270',
            discount: '-19%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '55m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Historic', 'City Center']
          },
          {
            id: 2,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Seville Villa',
            location: 'Seville, Spain',
            distance: '0.4 km from Cathedral',
            rating: 9.1,
            reviewCount: 38,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€350',
            originalPrice: '€420',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '120m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Historic', 'Luxury']
          },
          {
            id: 3,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Valencia Beach House',
            location: 'Valencia, Spain',
            distance: '0.2 km from beach',
            rating: 8.9,
            reviewCount: 31,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€280',
            originalPrice: '€340',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '85m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Beachfront', 'Modern']
          },
          {
            id: 4,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Granada Apartment',
            location: 'Granada, Spain',
            distance: '0.5 km from Alhambra',
            rating: 8.7,
            reviewCount: 29,
            reviewText: 'Very good',
            familyRated: false,
            price: '€180',
            originalPrice: '€220',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '50m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Historic', 'Cultural']
          },
          {
            id: 5,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Bilbao Loft',
            location: 'Bilbao, Spain',
            distance: '0.3 km from Guggenheim',
            rating: 8.5,
            reviewCount: 24,
            reviewText: 'Very good',
            familyRated: false,
            price: '€200',
            originalPrice: '€240',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '60m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Modern', 'Artsy']
          },
          {
            id: 6,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Córdoba Townhouse',
            location: 'Córdoba, Spain',
            distance: '0.2 km from Mezquita',
            rating: 8.6,
            reviewCount: 26,
            reviewText: 'Very good',
            familyRated: true,
            price: '€250',
            originalPrice: '€300',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '75m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Historic', 'Charming']
          },
          {
            id: 7,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Salamanca Studio',
            location: 'Salamanca, Spain',
            distance: '0.4 km from University',
            rating: 8.3,
            reviewCount: 22,
            reviewText: 'Very good',
            familyRated: false,
            price: '€160',
            originalPrice: '€190',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '40m²',
            eco: false,
            multiUnit: '4 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Student', 'Historic']
          },
          {
            id: 8,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Toledo Villa',
            location: 'Toledo, Spain',
            distance: '1.0 km from city center',
            rating: 8.9,
            reviewCount: 35,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€320',
            originalPrice: '€380',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '110m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Historic', 'Countryside']
          },
          {
            id: 9,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Málaga Beach Apartment',
            location: 'Málaga, Spain',
            distance: '0.1 km from beach',
            rating: 8.8,
            reviewCount: 33,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€290',
            originalPrice: '€350',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '80m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Beachfront', 'Family-friendly']
          },
          {
            id: 10,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Santiago Penthouse',
            location: 'Santiago de Compostela, Spain',
            distance: '0.3 km from Cathedral',
            rating: 9.0,
            reviewCount: 28,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€380',
            originalPrice: '€460',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '95m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Historic', 'Luxury']
          },
          {
            id: 11,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Zaragoza Apartment',
            location: 'Zaragoza, Spain',
            distance: '0.6 km from city center',
            rating: 8.4,
            reviewCount: 21,
            reviewText: 'Very good',
            familyRated: false,
            price: '€170',
            originalPrice: '€210',
            discount: '-19%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '45m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Free cancellation',
            tags: ['Modern', 'Budget']
          },
          {
            id: 12,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Murcia Villa',
            location: 'Murcia, Spain',
            distance: '2.0 km from city center',
            rating: 8.6,
            reviewCount: 25,
            reviewText: 'Very good',
            familyRated: true,
            price: '€240',
            originalPrice: '€290',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '90m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Villa', 'Quiet']
          },
          {
            id: 13,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Alicante Beach House',
            location: 'Alicante, Spain',
            distance: '0.3 km from beach',
            rating: 8.7,
            reviewCount: 30,
            reviewText: 'Very good',
            familyRated: true,
            price: '€260',
            originalPrice: '€320',
            discount: '-19%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '70m²',
            eco: false,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Beachfront', 'Modern']
          },
          {
            id: 14,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Oviedo Loft',
            location: 'Oviedo, Spain',
            distance: '0.5 km from city center',
            rating: 8.2,
            reviewCount: 19,
            reviewText: 'Very good',
            familyRated: false,
            price: '€150',
            originalPrice: '€180',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '35m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Loft', 'Budget']
          }
        ],
        totalCount: 142
      },
      // France country mapping
      'france': {
        accommodations: [
          {
            id: 1,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Lyon Apartment',
            location: 'Lyon, France',
            distance: '0.4 km from city center',
            rating: 8.7,
            reviewCount: 34,
            reviewText: 'Very good',
            familyRated: false,
            price: '€280',
            originalPrice: '€340',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 4 pers.',
            bedrooms: '2 bedroom',
            size: '70m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Modern', 'Cultural']
          },
          {
            id: 2,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Nice Beach Villa',
            location: 'Nice, France',
            distance: '0.2 km from beach',
            rating: 9.1,
            reviewCount: 41,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€450',
            originalPrice: '€540',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '120m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Beachfront', 'Luxury']
          },
          {
            id: 3,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Marseille Loft',
            location: 'Marseille, France',
            distance: '0.3 km from Old Port',
            rating: 8.5,
            reviewCount: 28,
            reviewText: 'Very good',
            familyRated: false,
            price: '€220',
            originalPrice: '€270',
            discount: '-19%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '55m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Free cancellation',
            tags: ['Historic', 'Trendy']
          },
          {
            id: 4,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Toulouse Apartment',
            location: 'Toulouse, France',
            distance: '0.5 km from city center',
            rating: 8.3,
            reviewCount: 25,
            reviewText: 'Very good',
            familyRated: false,
            price: '€200',
            originalPrice: '€240',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '50m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Modern', 'Budget']
          },
          {
            id: 5,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Nantes Villa',
            location: 'Nantes, France',
            distance: '1.2 km from city center',
            rating: 8.8,
            reviewCount: 32,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€320',
            originalPrice: '€380',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '95m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Villa', 'Quiet']
          },
          {
            id: 6,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Strasbourg Studio',
            location: 'Strasbourg, France',
            distance: '0.3 km from Cathedral',
            rating: 8.4,
            reviewCount: 23,
            reviewText: 'Very good',
            familyRated: false,
            price: '€180',
            originalPrice: '€220',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '40m²',
            eco: false,
            multiUnit: '4 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Historic', 'Charming']
          },
          {
            id: 7,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Montpellier Apartment',
            location: 'Montpellier, France',
            distance: '0.4 km from city center',
            rating: 8.6,
            reviewCount: 29,
            reviewText: 'Very good',
            familyRated: false,
            price: '€240',
            originalPrice: '€290',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '60m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Modern', 'Student']
          },
          {
            id: 8,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Bordeaux Penthouse',
            location: 'Bordeaux, France',
            distance: '0.2 km from city center',
            rating: 9.2,
            reviewCount: 37,
            reviewText: 'Outstanding',
            familyRated: true,
            price: '€520',
            originalPrice: '€620',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '130m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Long stay deal · Free cancellation',
            tags: ['Luxury', 'Wine']
          },
          {
            id: 9,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Lille Loft',
            location: 'Lille, France',
            distance: '0.6 km from city center',
            rating: 8.1,
            reviewCount: 20,
            reviewText: 'Very good',
            familyRated: false,
            price: '€190',
            originalPrice: '€230',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '45m²',
            eco: true,
            multiUnit: '3 more units available',
            policy: 'Free cancellation',
            tags: ['Loft', 'Artsy']
          },
          {
            id: 10,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Rennes Villa',
            location: 'Rennes, France',
            distance: '1.5 km from city center',
            rating: 8.9,
            reviewCount: 31,
            reviewText: 'Excellent',
            familyRated: true,
            price: '€380',
            originalPrice: '€460',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 6 pers.',
            bedrooms: '3 bedroom',
            size: '110m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Villa', 'Countryside']
          },
          {
            id: 11,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
            title: 'Reims Apartment',
            location: 'Reims, France',
            distance: '0.3 km from Cathedral',
            rating: 8.5,
            reviewCount: 26,
            reviewText: 'Very good',
            familyRated: false,
            price: '€210',
            originalPrice: '€250',
            discount: '-16%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '50m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Historic', 'Champagne']
          },
          {
            id: 12,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Dijon Studio',
            location: 'Dijon, France',
            distance: '0.4 km from city center',
            rating: 8.3,
            reviewCount: 22,
            reviewText: 'Very good',
            familyRated: false,
            price: '€170',
            originalPrice: '€200',
            discount: '-15%',
            nights: '7 nights',
            guests: 'Sleeps 2 pers.',
            bedrooms: '1 bedroom',
            size: '35m²',
            eco: false,
            multiUnit: '3 more units available',
            policy: 'Free cancellation · Mobile-only price',
            tags: ['Historic', 'Budget']
          },
          {
            id: 13,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Tours Apartment',
            location: 'Tours, France',
            distance: '0.5 km from city center',
            rating: 8.7,
            reviewCount: 28,
            reviewText: 'Very good',
            familyRated: false,
            price: '€230',
            originalPrice: '€280',
            discount: '-18%',
            nights: '7 nights',
            guests: 'Sleeps 3 pers.',
            bedrooms: '1 bedroom',
            size: '55m²',
            eco: true,
            multiUnit: '2 more units available',
            policy: 'Free cancellation',
            tags: ['Historic', 'Loire']
          },
          {
            id: 14,
            image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
            title: 'Angers Villa',
            location: 'Angers, France',
            distance: '1.0 km from city center',
            rating: 8.6,
            reviewCount: 24,
            reviewText: 'Very good',
            familyRated: true,
            price: '€300',
            originalPrice: '€360',
            discount: '-17%',
            nights: '7 nights',
            guests: 'Sleeps 5 pers.',
            bedrooms: '2 bedroom',
            size: '85m²',
            eco: true,
            multiUnit: '1 more unit available',
            policy: 'Free cancellation',
            tags: ['Villa', 'Historic']
          }
        ],
        totalCount: 134
      }
    };

    // Enhanced matching logic
    if (locationData[normalizedDestination]) {
      return locationData[normalizedDestination];
    }
    
    // Check for partial matches (e.g., "spain" matches "barcelona" if it contains "spain")
    for (const [key, data] of Object.entries(locationData)) {
      if (normalizedDestination.includes(key) || key.includes(normalizedDestination)) {
        return data;
      }
    }

    return locationData[destination] || {
      accommodations: [
        {
          id: 1,
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
          title: 'Beautiful Villa',
          location: 'Tuscany, Italy',
          distance: '2.1 km from city center',
          rating: 8.9,
          reviewCount: 34,
          reviewText: 'Excellent',
          familyRated: true,
          price: '€320',
          originalPrice: '€400',
          discount: '-20%',
          nights: '7 nights',
          guests: 'Sleeps 6 pers.',
          bedrooms: '3 bedroom',
          size: '120m²',
          eco: true,
          multiUnit: '2 more units available',
          policy: 'Free cancellation · Mobile-only price',
          tags: ['Villa', 'Countryside']
        },
        {
          id: 2,
          image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
          title: 'Modern Apartment',
          location: 'Amsterdam, Netherlands',
          distance: '0.8 km from city center',
          rating: 8.7,
          reviewCount: 28,
          reviewText: 'Very good',
          familyRated: false,
          price: '€280',
          originalPrice: '€340',
          discount: '-18%',
          nights: '7 nights',
          guests: 'Sleeps 4 pers.',
          bedrooms: '2 bedroom',
          size: '75m²',
          eco: true,
          multiUnit: '1 more unit available',
          policy: 'Free cancellation',
          tags: ['Modern', 'City Center']
        },
        {
          id: 3,
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
          title: 'Beach House',
          location: 'Santorini, Greece',
          distance: '0.3 km from beach',
          rating: 9.1,
          reviewCount: 42,
          reviewText: 'Outstanding',
          familyRated: true,
          price: '€450',
          originalPrice: '€550',
          discount: '-18%',
          nights: '7 nights',
          guests: 'Sleeps 5 pers.',
          bedrooms: '2 bedroom',
          size: '90m²',
          eco: false,
          multiUnit: '1 more unit available',
          policy: 'Long stay deal · Free cancellation',
          tags: ['Beachfront', 'Luxury']
        },
        {
          id: 4,
          image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
          title: 'Mountain Cabin',
          location: 'Swiss Alps, Switzerland',
          distance: '1.2 km from ski lift',
          rating: 8.8,
          reviewCount: 31,
          reviewText: 'Excellent',
          familyRated: true,
          price: '€380',
          originalPrice: '€460',
          discount: '-17%',
          nights: '7 nights',
          guests: 'Sleeps 6 pers.',
          bedrooms: '3 bedroom',
          size: '110m²',
          eco: true,
          multiUnit: '1 more unit available',
          policy: 'Free cancellation',
          tags: ['Mountain', 'Ski']
        },
        {
          id: 5,
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
          title: 'Historic Loft',
          location: 'Prague, Czech Republic',
          distance: '0.5 km from old town',
          rating: 8.4,
          reviewCount: 26,
          reviewText: 'Very good',
          familyRated: false,
          price: '€180',
          originalPrice: '€220',
          discount: '-18%',
          nights: '7 nights',
          guests: 'Sleeps 3 pers.',
          bedrooms: '1 bedroom',
          size: '55m²',
          eco: true,
          multiUnit: '3 more units available',
          policy: 'Free cancellation · Mobile-only price',
          tags: ['Historic', 'Artsy']
        },
        {
          id: 6,
          image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
          title: 'Luxury Penthouse',
          location: 'Dubai, UAE',
          distance: '0.2 km from beach',
          rating: 9.3,
          reviewCount: 19,
          reviewText: 'Outstanding',
          familyRated: true,
          price: '€650',
          originalPrice: '€780',
          discount: '-17%',
          nights: '7 nights',
          guests: 'Sleeps 8 pers.',
          bedrooms: '4 bedroom',
          size: '200m²',
          eco: false,
          multiUnit: '1 more unit available',
          policy: 'Long stay deal · Free cancellation',
          tags: ['Luxury', 'Beachfront']
        },
        {
          id: 7,
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
          title: 'Cozy Studio',
          location: 'Vienna, Austria',
          distance: '0.4 km from city center',
          rating: 8.2,
          reviewCount: 22,
          reviewText: 'Very good',
          familyRated: false,
          price: '€160',
          originalPrice: '€200',
          discount: '-20%',
          nights: '7 nights',
          guests: 'Sleeps 2 pers.',
          bedrooms: '1 bedroom',
          size: '35m²',
          eco: true,
          multiUnit: '4 more units available',
          policy: 'Free cancellation',
          tags: ['Cozy', 'Budget']
        },
        {
          id: 8,
          image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
          title: 'Countryside Villa',
          location: 'Provence, France',
          distance: '3.0 km from town center',
          rating: 9.0,
          reviewCount: 37,
          reviewText: 'Excellent',
          familyRated: true,
          price: '€420',
          originalPrice: '€500',
          discount: '-16%',
          nights: '7 nights',
          guests: 'Sleeps 6 pers.',
          bedrooms: '3 bedroom',
          size: '140m²',
          eco: true,
          multiUnit: '1 more unit available',
          policy: 'Free cancellation',
          tags: ['Countryside', 'Peaceful']
        },
        {
          id: 9,
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
          title: 'City Apartment',
          location: 'Berlin, Germany',
          distance: '0.6 km from Brandenburg Gate',
          rating: 8.6,
          reviewCount: 29,
          reviewText: 'Very good',
          familyRated: false,
          price: '€240',
          originalPrice: '€290',
          discount: '-17%',
          nights: '7 nights',
          guests: 'Sleeps 4 pers.',
          bedrooms: '2 bedroom',
          size: '70m²',
          eco: true,
          multiUnit: '2 more units available',
          policy: 'Free cancellation',
          tags: ['Modern', 'Cultural']
        },
        {
          id: 10,
          image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
          title: 'Seaside Cottage',
          location: 'Cornwall, UK',
          distance: '0.1 km from beach',
          rating: 8.9,
          reviewCount: 33,
          reviewText: 'Excellent',
          familyRated: true,
          price: '€350',
          originalPrice: '€420',
          discount: '-17%',
          nights: '7 nights',
          guests: 'Sleeps 5 pers.',
          bedrooms: '2 bedroom',
          size: '85m²',
          eco: true,
          multiUnit: '1 more unit available',
          policy: 'Long stay deal · Free cancellation',
          tags: ['Seaside', 'Charming']
        },
        {
          id: 11,
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
          title: 'Alpine Chalet',
          location: 'Austrian Alps, Austria',
          distance: '0.8 km from ski resort',
          rating: 9.2,
          reviewCount: 41,
          reviewText: 'Outstanding',
          familyRated: true,
          price: '€520',
          originalPrice: '€620',
          discount: '-16%',
          nights: '7 nights',
          guests: 'Sleeps 8 pers.',
          bedrooms: '4 bedroom',
          size: '180m²',
          eco: true,
          multiUnit: '1 more unit available',
          policy: 'Long stay deal · Free cancellation',
          tags: ['Alpine', 'Ski', 'Luxury']
        },
        {
          id: 12,
          image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
          title: 'Urban Loft',
          location: 'Lisbon, Portugal',
          distance: '0.3 km from city center',
          rating: 8.5,
          reviewCount: 24,
          reviewText: 'Very good',
          familyRated: false,
          price: '€200',
          originalPrice: '€240',
          discount: '-17%',
          nights: '7 nights',
          guests: 'Sleeps 3 pers.',
          bedrooms: '1 bedroom',
          size: '50m²',
          eco: true,
          multiUnit: '2 more units available',
          policy: 'Free cancellation',
          tags: ['Urban', 'Trendy']
        },
        {
          id: 13,
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
          title: 'Garden Villa',
          location: 'Tuscany, Italy',
          distance: '1.5 km from town center',
          rating: 8.7,
          reviewCount: 35,
          reviewText: 'Excellent',
          familyRated: true,
          price: '€380',
          originalPrice: '€460',
          discount: '-17%',
          nights: '7 nights',
          guests: 'Sleeps 6 pers.',
          bedrooms: '3 bedroom',
          size: '130m²',
          eco: true,
          multiUnit: '1 more unit available',
          policy: 'Free cancellation',
          tags: ['Garden', 'Rural']
        },
        {
          id: 14,
          image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop',
          title: 'Boutique Hotel',
          location: 'Florence, Italy',
          distance: '0.2 km from Duomo',
          rating: 9.1,
          reviewCount: 48,
          reviewText: 'Outstanding',
          familyRated: true,
          price: '€420',
          originalPrice: '€500',
          discount: '-16%',
          nights: '7 nights',
          guests: 'Sleeps 4 pers.',
          bedrooms: '2 bedroom',
          size: '80m²',
          eco: false,
          multiUnit: '3 more units available',
          policy: 'Free cancellation',
          tags: ['Boutique', 'Historic']
        }
      ],
      totalCount: 239
    };
  };

  const locationData = getLocationData(selectedDestination);
  const accommodations = locationData.accommodations;

  return (
    <div className="space-y-4">
      {accommodations.map((accommodation) => (
        <AccommodationCard key={accommodation.id} accommodation={accommodation} />
      ))}
    </div>
  );
};

export default SearchResults;





